# Generated by Django 2.0.7 on 2018-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ramkrishna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('City', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
            ],
        ),
    ]
