# Generated by Django 2.0.7 on 2018-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramkrishna',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=25),
        ),
    ]
