# Generated by Django 2.0.7 on 2018-07-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='update',
        ),
    ]
